### PR TITLE
Ref task#2823_4_5 Edit, Delete, Show career

### PR DESCRIPTION
**Pull request by hoanghung123vn**
Edit, Delete, Show career

### CODE REVIEW

**Comment by hoanghung123vn** [comment]
image

**Comment by hoanghung123vn** [comment]
ready

**Comment by thanhhungchu95** [comment]
conflicted

**Comment by hoanghung123vn** [comment]
ready

**Comment by thanhhungchu95** [comment]
conflicted
không sửa conflict à

**Comment by hoanghung123vn** [comment]
ready

**Pull request merged**
